# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
workflows:
  build:
    jobs:
      - self

jobs:
  self:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: "curl -X POST \
        -H 'Content-Type: application/json' \
        -d '{ \
          \"username\":\"ユーザー\", \
          \"content\":\"'\"${CIRCLE_BRANCH}\"'\" \
        }' ${DISCORD_WEB_HOOK_URL}"
